# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default='Temporary'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
